module.exports = {
home:'Startseite', journal:'Journal', breadcrumb:'Brotkrumennavigation', category:'Halloween-Geschenke', author:'Das SUPUZZ-Team', date:'22. September 2026', contents:'In diesem Ratgeber', faq:'Häufige Fragen', related:'Weitere Geschenk- und Spielideen zu Halloween', collection:'SUPUZZ-Kollektion entdecken', back:'Zurück zum Journal', read:'Ratgeber lesen', details:'Fotos und Set-Inhalt ansehen',
caption:'Produktfoto. Die Halloween-Geschichten und zusätzlichen Dekorationen sind Spielideen und nicht im Set enthalten.',
shoppingTitle:'Vor dem Kauf in den USA oder Kanada', shopping:'Prüfe die Altersangabe und den Inhalt der gewählten Packung. Die Produktseiten verlinken auf Amazon.com. Für Kanada solltest du die Lieferung an deine Adresse, Währung, Versandkosten und mögliche Einfuhrkosten prüfen; ein US-Angebot garantiert keine Lieferung nach Kanada. Vergleiche den voraussichtlichen Liefertermin mit deinem Festtermin, nicht nur mit dem 31. Oktober. Preise, Verfügbarkeit und Lieferzeiten können sich ändern.',
articles:[
{title:'Halloween-Geschenke für Kinder: Spielzeug statt Süßigkeiten',description:'Vergleiche 11 SUPUZZ-Bausets für Halloween: Dinosaurier, Meer, Eiswelt und Regenbogen-Bausteine. Geschenkideen für Überraschungskörbe und gemeinsames Spielen.',intro:'Ein Halloween-Geschenk kann bei den Interessen des Kindes beginnen: Dinosaurier, Meerestiere oder frei erfundene Bauwerke. Eine Karte mit einer kleinen Aufgabe macht daraus eine Überraschung für Oktober. Das Spielzeug lässt sich auch weiter nutzen, wenn die Dekoration wieder verstaut ist.',sections:[
['Den Anlass zuerst klären',`<p>Für ein eigenes Kind oder Enkelkind passt ein vollständiges Set, das ihr gemeinsam auspackt. Frage Geschwister, ob sie getrennte Projekte oder eine gemeinsame Landschaft möchten. Geschenke für eine Klasse und kleine Mitgaben an der Haustür brauchen eine andere Planung.</p><ul><li><strong>Familienüberraschung:</strong> ein Spielzeug und eine Einladung zum gemeinsamen Spielen.</li><li><strong>Geschenkkorb:</strong> erst das Geschenk, dann den Behälter wählen. Siehe {{a:1}}.</li><li><strong>Gruppenfeier:</strong> vorher fragen, ob einzelne Mitgaben oder gemeinsames Material gewünscht sind.</li></ul><p>Dieser Ratgeber stellt unsere SUPUZZ-Kollektion vor und ist keine unabhängige Rangliste. Die Halloween-Szenen sind Gestaltungsideen; Festdekoration ist nicht enthalten.</p>`],
['Regenbogen-Bausteine für freundliche Monster',`<p>Erfindet ein hilfsbereites Monster, ein Tor oder ein Fahrzeug für einen Kostümumzug. Bestimmte Halloween-Farben sind nicht nötig. Das Kind kann dem Wesen einen Namen geben und sein Kostüm erklären.</p>{{cards:soft-blocks-l2,soft-blocks-l3}}<p>Vergleiche 80 und 128 Teile danach, wie viel Baumaterial die Familie organisieren möchte. Beide Varianten enthalten einen Aufbewahrungskoffer; prüfe die ausgewählte Ausführung.</p>`],
['Dinosaurier für ein Dschungelabenteuer',`<p>Baut einen Weg zur Lichtung, auf der die Dinosaurier feiern. Der Raum kann hell bleiben: Die Geschichte bringt die Spannung. Eine dreiteilige Spielidee findest du in {{a:3}}.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 umfasst 41 Teile, L2 99 und L3 129. Die Stufe bezeichnet eine Produktversion, keine allgemeine Fähigkeitsstufe. Vergleiche die jeweiligen Inhaltsfotos.</p>`],
['Ein Unterwasserfest im Korallenriff',`<p>Für Kinder, die Tiere lieber mögen als Gespenster, bietet sich ein Unterwasserumzug an. Wer lädt ein, und wo treffen sich die Gäste? Ein Set reicht als Ausgangspunkt für eine Geschichte.</p>{{cards:ocean-l1,ocean-l2,ocean-l3}}<p>Die Varianten enthalten 38, 76 und 136 Teile. L2 und L3 haben eine Aufbewahrungsbox. Prüfe bei L2 die Altersangabe der konkreten Packung statt einer gemeinsamen Werbeabbildung.</p>`],
['Ein sanftes Rätsel in der Eiswelt',`<p>Eine Einladung liegt im Schnee. Wohin führt sie die Tiere? Nach Oktober lässt sich die Handlung einfach in ein Winterabenteuer verwandeln.</p>{{cards:ice-l1,ice-l2,ice-l3}}<p>Vergleiche 40, 79 und 136 Teile zusammen mit Altersangaben und Inhalt. Mehr Teile bedeuten nicht für jedes Kind mehr Freude.</p>`],
['Gemeinsame Spielzeit gehört dazu',`<p>Schreibe eine konkrete Einladung: „Am Samstag bauen wir das Zuhause deiner kleinen Kreatur.“ Weitere Vorschläge stehen in {{a:4}}.</p><p>Falls die Familie außerdem einen Sitzplatz für ihren Spielbereich sucht, kommt {{p:kids-chair-pink}} infrage. Angeboten wird ein einzelner Stuhl ohne Tisch. Prüfe die Maße im Verhältnis zum Kind und zum vorhandenen Tisch. Möbel sind eine optionale Ergänzung, keine Voraussetzung für ein Spielzeuggeschenk.</p>`]
],faq:[['Muss das Spielzeug ein Halloween-Motiv haben?','Nein. Eine Karte und eine Geschichte geben einem passenden Alltagsspielzeug einen saisonalen Anlass. Die vorgestellten Sets sind keine speziellen Halloween-Bausätze.'],['Was passt zu einem jüngeren Kind?','Beginne mit der Altersangabe der konkreten Packung. Berücksichtige danach Interessen und gewünschte Unterstützung. L1 oder weniger Teile bedeuten nicht, dass ein Set für jedes Kleinkind geeignet ist.']]},
{title:'Boo Basket für Kinder: Halloween-Korb ohne Süßigkeiten',description:'Stelle einen Halloween-Geschenkkorb mit Spielzeug, Karte und Spielidee zusammen. Vier Themen, praktische Budgettipps und ein persönlicher Gruß zum Anpassen.',intro:'Ein Boo Basket ist eine kleine Halloween-Überraschung in einem Korb, Beutel oder Karton. Ohne Süßigkeiten funktioniert er genauso: Wähle ein Hauptgeschenk, das das Kind nutzen wird, ergänze einen persönlichen Gruß und plane das erste Spiel. Viele kleine Füllartikel sind nicht nötig.',sections:[
['Drei Bausteine für den Geschenkkorb',`<ol><li><strong>Ein Hauptgeschenk:</strong> ein vollständiges Spielzeug mit passender Altersangabe.</li><li><strong>Ein persönliches Detail:</strong> eine Zeichnung, ein ausgeliehenes Buch zum gemeinsamen Lesen oder eine Karte mit dem Namen des Kindes.</li><li><strong>Eine Einladung:</strong> eine kurze Aktivität für die Zeit nach dem Auspacken.</li></ol><p>Wähle das Geschenk vor dem Behälter. Passt die Schachtel nicht hinein, lege die Karte in einen wiederverwendbaren Beutel und das verpackte Geschenk daneben. Verpackung und Anleitung bleiben zusammen; verteile keine losen Bauteile als Überraschungsfüllung.</p>`],
['Vier Themen mit einer ersten Aufgabe',`<h3>Werkstatt für freundliche Monster</h3><p>Vergleiche {{p:soft-blocks-l2}} und {{p:soft-blocks-l3}}. Schreibe: „Dein Monster braucht ein Zuhause. Wie sieht seine Haustür aus?“ Name und Charakter bestimmt das Kind.</p><h3>Dinosaurierexpedition</h3><p>Ergänze {{p:dinosaur-l1}} um eine gezeichnete Karte mit Startpunkt und Festplatz. Für mehr Teile vergleiche {{p:dinosaur-l2}} und {{p:dinosaur-l3}}, statt nur zum Füllen weitere Spielsachen hinzuzufügen.</p><h3>Unterwasserparty</h3><p>Wähle {{p:ocean-l1}} und zeichne eine Einladung für ein Meerestier. Wenn ohnehin ein größeres Geschenk geplant war, sieh dir {{p:ocean-l2}} und {{p:ocean-l3}} an.</p><h3>Eine Einladung im Schnee</h3><p>Vergleiche {{p:ice-l1}}, {{p:ice-l2}} und {{p:ice-l3}} nach Alter und Inhalt. Die Aufgabe lautet: „Jemand hat eine Einladung im Schnee hinterlassen. Wohin führt sie?“ Versprich keine Tiere oder Zubehörteile, ohne die Variante zu prüfen.</p>`],
['Das Budget vor dem Einkauf festlegen',`<p>Rechne Geschenk, Verpackung und Lieferung in den Gesamtbetrag ein. Nutze einen vorhandenen Behälter und gestalte die Karte selbst. Preise ändern sich; vergleiche die aktuellen Gesamtkosten, statt eine Stufe grundsätzlich für günstiger zu halten.</p><p>Bei Geschwistern zählt vergleichbare Aufmerksamkeit, nicht die gleiche Schachtelgröße. Möchten sie teilen, schreibe beide Namen auf die Karte und lass jedes Kind eine Rolle für das erste Bauprojekt wählen.</p>`],
['Ein Gruß zum Übernehmen und Anpassen',`<div class="quote-box"><p>„Deine Halloween-Überraschung ist da! Baue einen Ort für ein freundliches Wesen, gib ihm einen Namen und erzähle mir, wer zu Besuch kommt. Am Wochenende machen wir das zusammen.“</p></div><p>Frage die Eltern, bevor du einem Nachbarskind ein Geschenk hinterlässt. Nenne den Absender deutlich und mache daraus keine Pflicht, den nächsten Korb weiterzugeben. Für Schulgeschenke vorher die Lehrkraft fragen.</p><p>Alle Spielzeuge vergleicht {{a:0}}. Zur Unterscheidung zwischen Familiengeschenk und vielen kleinen Mitgaben hilft {{a:2}}.</p>`]
],faq:[['Wann verschenkt man einen Boo Basket?','Wenn es zu den Familienplänen im Oktober passt. Früh verschenkt bleibt mehr Zeit für das Spiel vor Halloween; am Feiertag selbst geht es ebenfalls.'],['Brauche ich viele kleine Spielsachen?','Nein. Ein vollständiges Spielzeug, ein Gruß und gemeinsame Zeit reichen. Ein vorhandener Beutel oder Karton eignet sich als Verpackung.']]},
{title:'Halloween ohne Süßigkeiten: Geschenkideen für Kinder',description:'Finde passende Halloween-Geschenke ohne Süßigkeiten für Familie, Haustür und Schule. Spielzeugideen, Planung und Informationen zum Teal Pumpkin Project.',intro:'Die passende Alternative zu Süßigkeiten hängt vom Empfänger ab. Ein vollständiges Bauset kann ein persönliches Geschenk für ein bekanntes Kind sein. Für viele Halloween-Besucher an der Haustür sind einzelne, leicht auszuwählende Kleinigkeiten meist eine andere und passendere Planung.',sections:[
['Persönliche Geschenke und Mitgaben unterscheiden',`<p>Frage vor dem Einkauf: Wie viele Kinder sind es? Kennst du ihr Alter? Spielen sie gemeinsam oder nehmen sie das Geschenk mit? Diese Antworten sind wichtiger als Kürbisse auf der Verpackung.</p><ul><li>Kind oder Enkelkind: nach bekannten Interessen auswählen.</li><li>Kleine Familienfeier: eine gemeinsame Aktivität erwägen.</li><li>Besucher an der Haustür: geeignete Einzeloptionen anbieten und Begleitpersonen mitentscheiden lassen.</li><li>Schulklasse: Regeln und Anzahl bestätigen lassen.</li></ul><p>Ein Bauset ist keine Packung einzelner Partygeschenke. Beim Aufteilen fehlen möglicherweise Bauteile, Anleitungen oder Altersangaben. Lass vollständige Sets zusammen.</p>`],
['Spielzeuge für ein persönliches Geschenk',`<h3>Für Tiergeschichten</h3><p>{{p:ocean-l1}} bietet eine Meereswelt, {{p:ice-l1}} eine Polarlandschaft. Ergänze eine selbst gemachte Einladung zum Tierfest und überlasse dem Kind die Handlung.</p><h3>Für Dinosaurierfans</h3><p>Zeichne zu {{p:dinosaur-l1}} eine Karte auf ein separates Blatt und plant eine Expedition. Varianten vergleicht {{a:3}}.</p><h3>Für eigene Erfindungen</h3><p>Verbinde {{p:soft-blocks-l2}} mit der Aufgabe, ein hilfsbereites Monster zu bauen. Der Spielauftrag schafft den Halloween-Bezug, ohne das Spielzeug auf einen Anlass zu begrenzen.</p>`],
['Nicht essbare Mitgaben vorbereiten',`<p>Sticker, Lesezeichen oder kleine Beschäftigungshefte sind mögliche Optionen, abhängig von Kennzeichnung und erwartetem Alter. Schätze die Menge anhand deiner Nachbarschaftserfahrung und halte Verpackungsinformationen für Erwachsene bereit.</p><p>Das <a href="https://www.foodallergy.org/our-initiatives/awareness-campaigns/teal-pumpkin-project">Teal Pumpkin Project von FARE</a> regt an, nicht essbare Alternativen in einer separaten Schale anzubieten. Die offizielle Website erklärt die Teilnahme. Ein türkisfarbener Kürbis weist auf solche Optionen hin; er zertifiziert kein Spielzeug.</p><p>Ohne Süßigkeiten bedeutet nicht automatisch frei von Allergenen. Mache keine pauschalen Material- oder Eignungsversprechen. Wenn du auch Süßigkeiten anbietest, halte die nicht essbaren Optionen getrennt.</p>`],
['Eine persönliche Geste statt möglichst vieler Dinge',`<p>Frage nach dem aktuellen Lieblingstier oder der liebsten Geschichte. Verpacke ein vollständiges Set und schreibe das erste Abenteuer sowie einen gemeinsamen Spieltermin auf eine Karte.</p><p>Möchte die Familie weniger Gegenstände, schenke einen Bibliotheksbesuch, einen Malnachmittag oder Zeit zum Umbauen eines vorhandenen Spielzeugs. Ohne Süßigkeiten zu feiern erfordert keinen Einkauf.</p><p>Verpackungsideen gibt es in {{a:1}}, die Spielzeugauswahl in {{a:0}} und Hinweise für Gruppen in {{a:5}}.</p>`]
],faq:[['Kann ich einzelne Set-Teile an Halloween-Besucher verteilen?','Ein vollständiges Set eignet sich besser als persönliches Geschenk oder für eine geplante Aktivität. Lose Einzelteile sind keine vollständigen kleinen Bausets.'],['Ist ohne Süßigkeiten automatisch für jede Allergie geeignet?','Nein. Prüfe den konkreten Artikel und frage die Begleitperson. Nicht essbare Alternativen sind keine allgemeine Sicherheitsgarantie.']]},
{title:'Dinosaurier zu Halloween verschenken: Bausets und Ideen',description:'Vergleiche Dinosaur Jungle L1, L2 und L3 als Halloween-Geschenk. Mit selbst gezeichneter Karte und einem freundlichen Abenteuer in drei Schritten.',intro:'Für ein dinosaurierbegeistertes Kind kann Halloween zur Reise in eine erfundene Urzeit werden. Ein Bauset, eine gezeichnete Karte und eine Einladung zum freundlichen Fest reichen für den Anfang. Die Geschichte sorgt für die saisonale Stimmung.',sections:[
['Die drei Dinosaurier-Sets vergleichen',`<p>Wähle nach Platz, Interessen und der Menge an Teilen, die die Familie ordnen möchte. Die Stufe bezeichnet eine Version und keine allgemeingültige Fähigkeit.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 bietet 41 Teile für eine überschaubare Szene, L2 99 und L3 129. Der Katalog nennt 3 Jahre und älter; prüfe die ausgewählte Packung. Gemeinsame Serienbilder können andere Anordnungen zeigen. Vergleiche das genaue Inhaltsfoto und leite einen Aufbewahrungskoffer nicht aus der Teilezahl ab.</p>`],
['Ein Halloween-Abenteuer in drei Schritten',`<h3>1. Die Einladung kommt an</h3><p>Schreibe: „Die Dinosaurier feiern eine Kostümparty. Kannst du ihnen einen Treffpunkt bauen?“ Zeichne Start und Lichtung auf ein separates Blatt und lass das Kind den Plan verändern.</p><h3>2. Einen freundlichen Weg anlegen</h3><p>Ordnet Pflanzen und Dschungelteile zu einer Route. Wer kommt zuerst? Wo warten die Gäste? Auch eine gedachte Nachtexpedition funktioniert in einem gut beleuchteten Raum.</p><h3>3. Ein kleines Problem lösen</h3><p>Ein Gast hat sich verlaufen. Bitte das Kind, ein Landschaftsteil zu versetzen, damit der Gast das Fest findet. Am Ende kommen alle zusammen; danach kann das Kind die Geschichte neu erzählen.</p><p>Dies sind kreative Vorschläge, keine mitgelieferten Aufgaben oder garantierten Bauformen. Nutze die Teile deiner Version. Karten und Einladungen entstehen zusätzlich zu Hause.</p>`],
['Die Präsentation passend gestalten',`<p>Für ein Enkelkind ergänzt du den nächsten gemeinsamen Spieltermin. Frage Geschwister, ob sie eine Landschaft teilen oder eigene Projekte bauen möchten. Mag das Kind keine Gruselbilder, wird daraus einfach ein Herbstfest.</p><p>Bewahre Verpackung und Anleitung auf. Für einen Geschenkkorb zuerst die Schachtel messen und {{a:1}} lesen. Ein großer Korb ist kein Grund für zusätzliche Spielzeuge.</p>`],
['Nach Halloween weiterspielen',`<p>Beim nächsten Mal geht es um eine Dschungelrettung, einen Gartenbesuch oder ein Picknick. Baut die Route um und fragt, was diesmal anders sein soll. Der Anlass verändert sich, das Spielzeug bleibt.</p><p>Für Meeres- und Polartierfans bietet {{a:0}} Alternativen. Mit bereits vorhandenem Material helfen die Vorschläge in {{a:4}}.</p>`]
],faq:[['Sind das spezielle Halloween-Dinosaurierkits?','Nein. Es handelt sich um Dinosaur-Jungle-Bausets. Einladung, Landkarte und Partygeschichte sind freiwillige Ergänzungen für zu Hause.'],['Braucht ein älteres Kind immer das größte Set?','Nicht unbedingt. Beachte die Altersangabe und danach Interessen, Platz und die Freude am Organisieren vieler Teile.']]},
{title:'5 Halloween-Spielideen mit Bausteinen für Kinder',description:'Baut ein freundliches Monster, ein Partytor, einen Dinosaurierpfad, einen Meeresumzug und ein Polarrätsel. Fünf anpassbare Ideen für Familien.',intro:'Ein kleines Problem und eine Geschichte machen aus einer normalen Baurunde ein Halloween-Spiel. Passe diese fünf Anregungen an altersgerechte Teile an, die bereits vorhanden sind. Das Kind entscheidet, wie die Szene aussehen soll; eine feste Vorlage ist nicht nötig.',sections:[
['Eine kurze Familienrunde vorbereiten',`<p>Wählt eine Aufgabe, räumt eine ebene Spielfläche frei und lasst Platz für unbenutzte Teile. Papier und Stifte für Einladungen oder Schilder liegen separat vom Spielzeug bereit.</p><p>Als flexibler Plan eignen sich 25 Minuten: fünf für die Geschichte, fünfzehn zum Bauen und Ändern, fünf zum Erzählen und Aufräumen. Das ist ein Organisationsvorschlag und keine verlangte Aufmerksamkeitsspanne. Ihr könnt früher aufhören oder länger spielen.</p>`],
['1. Ein hilfsbereites Monster',`<p><strong>Die Aufgabe:</strong> „Dieses Monster hilft bei der Party. Was tut es?“ Baut eine Figur, ein Fahrzeug oder ein Werkzeug. Für ein Geschenk kannst du {{p:soft-blocks-l2}} und {{p:soft-blocks-l3}} vergleichen.</p><p><strong>Die Veränderung:</strong> Baut ein Teil um, damit eine gedachte Einladung transportiert oder eine Tür passiert werden kann. Das Kind erklärt die Änderung; die Form muss nicht sofort als Monster erkennbar sein.</p>`],
['2. Ein Tor für den Kostümumzug',`<p><strong>Die Aufgabe:</strong> „Die Gäste brauchen einen Eingang.“ Baut ein Tor und überlegt, welcher imaginäre Gast hindurchpassen soll. Passt Öffnung und Basis bei Bedarf an.</p><p><strong>Die Veränderung:</strong> Baut mit denselben Teilen einen breiteren Eingang und vergleicht beide Lösungen. Falls eine Figur hilft, genügt eine bereits vorhandene, altersgerechte.</p>`],
['3. Ein Pfad für Dinosaurier',`<p><strong>Die Aufgabe:</strong> „Der Dinosaurier muss die Party finden.“ Mit {{p:dinosaur-l1}} oder vorhandenen Tieren gestaltet ihr Start, Weg und Ziel. Eine separate Zeichnung kann als Karte dienen.</p><p><strong>Die Veränderung:</strong> Der Weg ist versperrt; versetzt die Landschaft und findet eine andere Route. Die ausführliche Geschichte steht in {{a:3}}.</p>`],
['4. Ein Unterwasserumzug',`<p><strong>Die Aufgabe:</strong> „Die Meerestiere brauchen einen Treffpunkt.“ Nutzt {{p:ocean-l1}} oder zeichnet die Szene. Wer führt den Umzug an, und wo warten die Gäste?</p><p><strong>Die Veränderung:</strong> Ordnet einige Teile nach Farbe oder Form zu einer Folge. Das Kind setzt sie fort oder erfindet eine andere, so einfach oder komplex wie gewünscht.</p>`],
['5. Eine Einladung im Schnee',`<p><strong>Die Aufgabe:</strong> „Im Schnee liegt ein Brief. Für wen ist er?“ Nutzt {{p:ice-l2}} oder eine andere Tierlandschaft und erzählt, wie die Einladung dorthin gekommen ist.</p><p><strong>Die Veränderung:</strong> Ergänzt abwechselnd ein Ereignis. Ein Gast verirrt sich und das Kind entscheidet, wie ihm geholfen wird. Bleibt bei einer beruhigenden Geschichte, wenn das besser passt.</p>`],
['Die Lieblingsaufgabe als Geschenkidee',`<p>Schreibe den beliebtesten Spielauftrag auf eine Karte für ein späteres Geschenk. Prüfe über {{a:0}} den Inhalt, bevor du eine bestimmte Konstruktion versprichst. Die Ideen sind kreative Vorschläge, keine Aussagen über gemessene Lernerfolge.</p><p>In Gruppen wechseln sich Planung, Bauen und Erzählen ab. Hinweise zu Material und Aufräumen bietet {{a:5}}.</p>`]
],faq:[['Benötige ich alle vier Kollektionen?','Nein. Wähle eine Aufgabe und passe sie an vorhandenes, altersgerechtes Material an. Fehlende Szenenelemente kannst du auf Papier zeichnen.'],['Ist Halloween-Dekoration enthalten?','Hier wird kein Festzubehör zugesagt. Karten, Schilder und Einladungen sind freiwillige Ergänzungen; den tatsächlichen Inhalt zeigt die Produktseite.']]},
{title:'Halloween-Geschenke für die Klasse ohne Süßigkeiten',description:'Plane Halloween-Mitgaben mit Zustimmung der Lehrkraft. Einzelgeschenke, gemeinsame Bausets und ein übersichtlicher Ablauf für Spiel und Aufräumen.',intro:'Beginne mit den Regeln der Lehrkraft, der Kinderzahl und dem Zweck des Geschenks. Eine kleine Mitgabe, ein gespendetes Klassenspielzeug und eine gemeinsame Partyaktivität sind verschiedene Vorhaben. Ein klares Ziel vereinfacht die Organisation.',sections:[
['Vor dem Einkauf nachfragen',`<p>Kläre, ob die Schule Halloween feiert, ein Herbstthema bevorzugt oder keine Geschenke annimmt. Frage nach Alter, erlaubten Materialien, Regeln zu Lebensmitteln und verfügbarer Zeit. Brauchen alle das gleiche kleine Geschenk oder wäre gemeinsames Material hilfreicher?</p><p>Eine kurze Nachricht reicht: „Wäre eine Aktivität ohne Lebensmittel oder ein Bauset willkommen? Für wie viele Kinder und welche Materialien oder Themen sollen wir vermeiden?“ Warte mit der Mengenplanung auf die Antwort.</p>`],
['Einzelne Mitgaben einfach halten',`<p>Erwäge genehmigte und altersgerechte Sticker, Lesezeichen, Stifte oder Beschäftigungsblätter. Die Lehrkraft sollte sie nicht während der Feier zusammenbauen müssen. Plane mit der bestätigten Anzahl und besprecht zusätzliche Gäste.</p><p>Teile ein Bauset nicht in Beutel mit losen Teilen auf. Es könnten Komponenten, Anleitungen und Alterskennzeichnungen fehlen. Ein vollständiges SUPUZZ-Set eignet sich eher als abgestimmte Spende oder für eine geplante Baustation.</p><p>{{a:2}} unterscheidet Familiengeschenke und Mitgaben für viele Besucher. Was zu einem bekannten Kind passt, eignet sich nicht automatisch für eine ganze Klasse.</p>`],
['Eine gemeinsame Baustation planen',`<p>Frage zuerst nach vorhandenen Materialien. Wenn eine Spende gewünscht ist, vergleiche {{p:soft-blocks-l3}} für erfundene Figuren oder {{p:ocean-l2}} und {{p:ice-l2}} für Tiergeschichten. Prüfe Alter und genaue Inhalte mit der Lehrkraft.</p><p>Die Teilezahl legt die Gruppengröße nicht fest. Die Lehrkraft entscheidet nach Platz, Begleitung und Aufgabe. Stelle nur so viel Material bereit, wie bequem auf die Fläche passt.</p><ol><li>Die Geschichte vorstellen: Ein freundliches Wesen sucht einen Ort für ein Herbstfest.</li><li>Verschiedene Rollen anbieten: planen, bauen, zeichnen oder erzählen.</li><li>Die Beteiligung wechseln lassen, damit alle Ideen beitragen können.</li><li>Das Ergebnis und seine Veränderungen vorstellen.</li><li>Teile zurücklegen und Anleitung beim Set lassen.</li></ol>`],
['Übergänge und Aufräumen einplanen',`<p>Schlage drei Minuten Einführung, zehn Minuten Bauen und fünf Minuten für Vorstellung und Ordnung vor. Die Lehrkraft passt den Ablauf an. Dekoration sollte das Einsammeln der Teile nicht behindern.</p><p>Bestimmt den Aufbewahrungsplatz vor Beginn. Nutzt die Box, falls die Variante eine enthält; andernfalls vereinbart einen geeigneten Behälter. Klärt, ob das Material in der Klasse bleibt oder zurück zur Familie geht.</p>`],
['Eine Variante ohne Grusel anbieten',`<p>Ein Dschungeltreffen oder Tierumzug braucht weder Gespenster noch Kostüme. Wer nicht bauen möchte, kann zeichnen oder erzählen. Orientiere dich an den Vorgaben der Lehrkraft.</p><p>Fertige Anregungen liefert {{a:4}}. Vergleiche die Kollektion in {{a:0}}, sobald geklärt ist, dass eine Spielzeugspende sinnvoll ist.</p>`]
],faq:[['Soll jedes Kind ein vollständiges Set erhalten?','Nur wenn einzelne Komplettsets zum abgestimmten Plan und Budget passen. Häufig sind einfache Mitgaben oder eine gemeinsame Aktivität praktischer.'],['Kann die Aktivität ganz ohne Halloween auskommen?','Ja. Macht daraus ein Herbsttreffen oder einen Tierumzug. Die Spielzeuge benötigen keine Halloween-Geschichte.']]}
]};
