module.exports = {
home:'Inicio', journal:'Diario', breadcrumb:'Ruta de navegación', category:'Regalos de Halloween', author:'Equipo SUPUZZ', date:'22 de septiembre de 2026', contents:'En esta guía', faq:'Preguntas frecuentes', related:'Más ideas de regalos y juegos de Halloween', collection:'Explorar la colección SUPUZZ', back:'Volver al Diario', read:'Leer la guía', details:'Ver fotos y contenido del set',
caption:'Foto del producto. Las historias de Halloween y las decoraciones adicionales son propuestas de juego; no forman parte del set.',
shoppingTitle:'Antes de comprar en Estados Unidos o Canadá', shopping:'Revisa la edad indicada y el contenido del paquete seleccionado. Las páginas de producto enlazan a Amazon.com. Si compras desde Canadá, confirma la entrega a tu dirección, la moneda, el envío y los posibles gastos de importación: una ficha estadounidense no garantiza la entrega en Canadá. Consulta la fecha estimada de llegada para tu celebración, no solo para el 31 de octubre. Los precios, las existencias y los plazos pueden cambiar.',
articles:[
{title:'Juguetes para regalar en Halloween: guía para niños',description:'Compara 11 sets SUPUZZ para regalar en Halloween sin dulces: dinosaurios, océano, hielo y bloques arcoíris. Ideas para canastas y juegos en familia.',intro:'Un regalo de Halloween puede empezar por lo que ya le gusta al niño: dinosaurios, animales marinos o inventar construcciones. Añade una tarjeta con un pequeño reto y un juguete de uso cotidiano se convierte en una sorpresa de octubre que seguirá teniendo vida después de la fiesta.',sections:[
['Elige según la ocasión',`<p>Para un hijo o nieto, busca un set completo que puedan abrir y explorar juntos. Para hermanos, pregunta si prefieren proyectos separados o una escena compartida. Una fiesta escolar o una puerta con muchos visitantes necesita un plan distinto al de un regalo personal.</p><ul><li><strong>Sorpresa familiar:</strong> un juguete y una invitación a jugar.</li><li><strong>Canasta de Halloween:</strong> elige primero el regalo y después el recipiente. Consulta {{a:1}}.</li><li><strong>Celebración en grupo:</strong> pregunta si convienen recuerdos individuales o materiales compartidos.</li></ul><p>Esta es una guía de la colección SUPUZZ, no una clasificación independiente. Las escenas de Halloween son ideas para crear; las decoraciones de la fiesta no están incluidas.</p>`],
['Bloques arcoíris para inventar monstruos amistosos',`<p>Propón un monstruo que ayuda a los invitados, una puerta o un vehículo para un desfile imaginario. No hace falta respetar colores de Halloween: el niño puede poner nombre al personaje y explicar su disfraz.</p>{{cards:soft-blocks-l2,soft-blocks-l3}}<p>Compara 80 y 128 piezas según la cantidad de material que quieran organizar. Ambos sets tienen maletín de almacenamiento; confirma siempre la opción seleccionada.</p>`],
['Dinosaurios para una aventura en la selva',`<p>Construyan un camino hasta el lugar de una fiesta prehistórica. Mantengan la habitación iluminada y dejen que la historia aporte el misterio. En {{a:3}} encontrarás una aventura de tres pasos.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 tiene 41 piezas, L2 tiene 99 y L3 tiene 129. El nivel identifica una versión, no una medida universal de habilidad. Compara las fotos del contenido de cada paquete.</p>`],
['Arrecifes para una fiesta submarina',`<p>Si prefiere animales a fantasmas, imaginen un desfile bajo el agua. Pregunta quién organiza la fiesta y dónde esperan los invitados. Un solo set puede ser suficiente para empezar.</p>{{cards:ocean-l1,ocean-l2,ocean-l3}}<p>Las versiones incluyen 38, 76 y 136 piezas respectivamente. L2 y L3 tienen caja de almacenamiento. Para L2, revisa la edad en el paquete elegido en lugar de guiarte por imágenes compartidas.</p>`],
['Mundos de hielo para un misterio tranquilo',`<p>Una invitación aparece en la nieve: ¿adónde lleva a los animales? La historia puede convertirse en una aventura de invierno cuando termine octubre.</p>{{cards:ice-l1,ice-l2,ice-l3}}<p>Compara los sets de 40, 79 y 136 piezas junto con sus edades y contenidos. Más piezas no significan que todos los niños vayan a disfrutar más.</p>`],
['Completa el regalo con tiempo para jugar',`<p>Escribe una invitación concreta: «El sábado construiremos la casa de tu criatura». Encuentra más propuestas en {{a:4}}.</p><p>Si la familia también necesita un asiento para sus actividades, consulta {{p:kids-chair-pink}}. Se vende una sola silla, sin mesa. Comprueba las medidas del niño y de la mesa existente; el mobiliario es una compra opcional, no un requisito para regalar bloques.</p>`]
],faq:[['¿El juguete tiene que ser de Halloween?','No. Un juguete relacionado con los intereses del niño puede adquirir un sentido festivo con una tarjeta y una historia. Estos sets no son kits específicos de Halloween.'],['¿Qué elegir para un niño pequeño?','Empieza por la edad del paquete exacto. Después considera sus intereses y la ayuda que necesita. L1 o un número menor de piezas no significan que sea adecuado para cualquier niño pequeño.']]},
{title:'Boo basket para niños: canastas de Halloween sin dulces',description:'Prepara una canasta de Halloween con un juguete, una tarjeta y una actividad. Cuatro temas para niños, consejos de presupuesto y una nota para copiar.',intro:'Un boo basket es una pequeña sorpresa de Halloween presentada en una canasta, bolsa o caja. Para hacerlo sin dulces, elige un regalo principal que el niño vaya a usar, añade una nota personal y planea el primer juego. No necesitas llenarlo de pequeños objetos.',sections:[
['Tres elementos para una canasta completa',`<ol><li><strong>Un regalo principal:</strong> un juguete completo con una edad indicada adecuada.</li><li><strong>Un detalle personal:</strong> un dibujo, un libro de la biblioteca para leer juntos o una nota con su nombre.</li><li><strong>Una invitación:</strong> una actividad breve para compartir al abrirlo.</li></ol><p>Compra o elige el regalo antes de buscar el recipiente. Si la caja no cabe, coloca la tarjeta en una bolsa reutilizable y el juguete envuelto al lado. Conserva el embalaje y las instrucciones; no repartas piezas sueltas como relleno sorpresa.</p>`],
['Cuatro temas con una primera misión',`<h3>Taller de monstruos amistosos</h3><p>Compara {{p:soft-blocks-l2}} y {{p:soft-blocks-l3}}. Escribe: «Tu monstruo necesita una casa. ¿Cómo será su puerta?». Deja que el niño invente su nombre y personalidad.</p><h3>Expedición de dinosaurios</h3><p>Acompaña {{p:dinosaur-l1}} con un mapa que muestre el inicio y el lugar de una fiesta. Si buscas más piezas, compara {{p:dinosaur-l2}} y {{p:dinosaur-l3}} antes de añadir otro juguete solo para llenar la canasta.</p><h3>Fiesta bajo el mar</h3><p>Elige {{p:ocean-l1}} y dibuja una invitación para un animal marino. Si ya planeabas un regalo mayor, revisa {{p:ocean-l2}} y {{p:ocean-l3}}.</p><h3>Una carta en la nieve</h3><p>Compara {{p:ice-l1}}, {{p:ice-l2}} y {{p:ice-l3}} según edad y contenido. Propón: «Alguien dejó una invitación en la nieve. ¿Adónde conduce?». No prometas animales o accesorios sin comprobar la versión.</p>`],
['Fija el presupuesto antes de comprar',`<p>Cuenta el regalo, el envoltorio y la entrega dentro del total. Reutiliza un recipiente de casa y prepara la nota tú mismo. Los precios cambian: compara el importe actual, sin asumir que un nivel siempre cuesta menos.</p><p>Para hermanos, busca una atención equivalente, no cajas idénticas. Si prefieren compartir, escribe ambos nombres y deja que cada uno elija un papel para la primera construcción.</p>`],
['Una nota que puedes adaptar',`<div class="quote-box"><p>«¡Llegó tu sorpresa de Halloween! Construye un lugar para una criatura amistosa, ponle nombre y cuéntame quién viene de visita. Este fin de semana lo hacemos juntos».</p></div><p>Antes de dejar un regalo a un vecino, consulta con sus padres. Indica quién lo envía y no conviertas la tradición en una obligación de regalar a otra familia. Para la escuela, pregunta al docente.</p><p>Compara todos los juguetes en {{a:0}}. Si estás decidiendo entre un regalo familiar y recuerdos para muchos visitantes, lee {{a:2}}.</p>`]
],faq:[['¿Cuándo se entrega un boo basket?','Cuando encaje en los planes familiares de octubre. Entregarlo antes permite usar la actividad durante el mes; regalarlo el mismo Halloween también funciona.'],['¿Necesito muchos juguetes pequeños?','No. Un juguete completo, una nota y tiempo para jugar forman un regalo suficiente. Puedes reutilizar una bolsa o caja.']]},
{title:'Regalos de Halloween sin dulces: ideas para niños',description:'Elige regalos de Halloween sin dulces para familia, visitas y fiestas escolares. Ideas de juguetes, planificación y recursos oficiales de Teal Pumpkin.',intro:'La mejor alternativa a los dulces depende del destinatario. Un set de construcción completo puede ser un regalo personal para un niño que conoces. Para recibir a muchos visitantes en Halloween, convienen opciones individuales fáciles de repartir y de revisar por sus cuidadores.',sections:[
['Distingue un regalo personal de un recuerdo',`<p>Antes de comprar, pregunta cuántos niños recibirán algo, si conoces sus edades y si usarán el regalo juntos o se lo llevarán a casa. Estas respuestas importan más que los dibujos de Halloween del envoltorio.</p><ul><li>Un hijo o nieto: elige según un interés conocido.</li><li>Una reunión pequeña: considera una actividad compartida.</li><li>Visitantes que piden dulces: prepara opciones individuales apropiadas y deja elegir a los cuidadores.</li><li>Una clase: confirma normas y cantidad de alumnos.</li></ul><p>Un set de construcción no es un paquete de recuerdos para repartir. Dividirlo puede dejar construcciones incompletas y separar a los niños de las instrucciones y etiquetas.</p>`],
['Juguetes para un regalo personal',`<h3>Historias de animales</h3><p>{{p:ocean-l1}} propone un escenario marino y {{p:ice-l1}} uno polar. Añade una invitación casera para una fiesta de animales y deja que el niño decida el relato.</p><h3>Aventuras de dinosaurios</h3><p>Con {{p:dinosaur-l1}}, dibuja un mapa en otra hoja y organiza una expedición por la selva. Compara las versiones en {{a:3}}.</p><h3>Construcciones inventadas</h3><p>Acompaña {{p:soft-blocks-l2}} con el reto de crear un monstruo que ayuda a los demás. La propuesta aporta el ambiente de octubre sin limitar el juguete a una sola celebración.</p>`],
['Planifica las opciones no alimentarias',`<p>Puedes considerar pegatinas, separadores de libros o pequeños cuadernos de actividades, según sus etiquetas y las edades esperadas. Estima la cantidad con la experiencia de tu vecindario y conserva los envoltorios para que los adultos los revisen.</p><p>El <a href="https://www.foodallergy.org/our-initiatives/awareness-campaigns/teal-pumpkin-project">Teal Pumpkin Project de FARE</a> propone ofrecer opciones no alimentarias en un recipiente separado. Su página oficial explica cómo participar. La calabaza turquesa señala que hay alternativas; no certifica ningún juguete.</p><p>Sin dulces no significa automáticamente libre de alérgenos. No hagas promesas generales sobre materiales o idoneidad para todos los niños. Si también ofreces golosinas, mantén separadas las opciones no alimentarias.</p>`],
['Haz que el regalo sea personal',`<p>Pregunta por su animal o historia favorita. Envuelve un set completo y escribe la primera aventura en una tarjeta, junto con una invitación a jugar contigo.</p><p>Si la familia no quiere más objetos, ofrece una visita a la biblioteca, una tarde de dibujo o tiempo para reconstruir un juguete que ya tienen. Celebrar sin dulces no obliga a comprar.</p><p>Consulta {{a:1}} para la presentación, {{a:0}} para comparar juguetes y {{a:5}} para eventos escolares.</p>`]
],faq:[['¿Puedo repartir piezas de un set a quienes piden dulces?','Es preferible mantener el set completo para un regalo personal o una actividad organizada. Las piezas sueltas no equivalen a pequeños sets completos.'],['¿Una alternativa sin dulces es segura para cualquier alergia?','No. Revisa el producto específico y consulta al cuidador. Ofrecer opciones no alimentarias no constituye una garantía universal.']]},
{title:'Dinosaurios para regalar en Halloween: sets y juegos',description:'Compara Dinosaur Jungle L1, L2 y L3 para un regalo de Halloween. Añade un mapa y una aventura en tres pasos para niños que disfrutan los dinosaurios.',intro:'Para un niño aficionado a los dinosaurios, Halloween puede convertirse en una expedición prehistórica. Un set de bloques, un mapa dibujado y una invitación a una fiesta amistosa bastan para empezar. La historia aporta el ambiente de temporada.',sections:[
['Compara las tres versiones',`<p>Elige según el espacio de juego, el interés del niño y la cantidad de piezas que la familia quiera organizar. El nivel nombra una versión, no una habilidad universal.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 reúne 41 piezas para una escena más concentrada; L2 ofrece 99 y L3, 129. El catálogo indica 3 años o más; comprueba el paquete seleccionado. Las imágenes de la serie pueden mostrar otras combinaciones: utiliza la foto del contenido de la versión exacta. No supongas que incluye maletín por el número de piezas.</p>`],
['Una aventura de Halloween en tres pasos',`<h3>1. Llega la invitación</h3><p>Escribe: «Los dinosaurios celebran una fiesta de disfraces. ¿Puedes construir un lugar para reunirse?». Dibuja un inicio y un claro en una hoja aparte, dejando espacio para que el niño cambie el plan.</p><h3>2. Prepara un camino amistoso</h3><p>Organiza las plantas y elementos de la selva para sugerir una ruta. Pregunta quién llega primero y dónde esperan los invitados. La habitación puede estar bien iluminada aunque el relato sea una expedición nocturna.</p><h3>3. Resuelve un pequeño problema</h3><p>Imagina que un invitado se perdió. Invita al niño a mover una parte del escenario para ayudarlo a llegar. Termina con todos reunidos y deja que cuente de nuevo la historia.</p><p>Son propuestas creativas, no actividades incluidas ni construcciones garantizadas. Utiliza las piezas de la versión que tienes; el mapa y las tarjetas se preparan por separado.</p>`],
['Adapta el regalo a quien lo recibe',`<p>Para un nieto, añade la fecha en que jugarán juntos. Para hermanos, pregunta si quieren compartir la escena o crear proyectos propios. Si no le gustan los sustos, conviértelo en una reunión de otoño.</p><p>Conserva el embalaje y las instrucciones. Para una canasta, mide primero la caja y consulta {{a:1}}. Un recipiente grande no es motivo para añadir más juguetes.</p>`],
['Sigue jugando después de octubre',`<p>La próxima vez, cambia el relato por un rescate en la selva, una visita al jardín o un picnic. Reorganiza el camino y pregunta qué debería ser distinto. Un juguete cotidiano permite cambiar de historia sin cambiar de regalo.</p><p>Si prefiere animales marinos o polares, compara otras opciones en {{a:0}}. Para jugar con materiales disponibles, prueba {{a:4}}.</p>`]
],faq:[['¿Son kits de dinosaurios exclusivos de Halloween?','No. Son sets de construcción de la colección Dinosaur Jungle. La invitación, el mapa y la fiesta son ideas opcionales para añadir en casa.'],['¿Un niño mayor necesita siempre el set más grande?','No necesariamente. Respeta la edad del paquete y considera sus intereses, el espacio y cuánto disfruta organizar piezas.']]},
{title:'5 actividades de Halloween con bloques para niños',description:'Construye un monstruo amistoso, una entrada, un sendero de dinosaurios, un desfile marino y un misterio polar. Cinco juegos de Halloween en familia.',intro:'Una pequeña misión y una historia pueden transformar una sesión de construcción en un juego de Halloween. Adapta estas cinco propuestas a las piezas apropiadas para la edad que ya tengas. El niño decide cómo será el resultado: no hay un modelo único que copiar.',sections:[
['Prepara una sesión breve en familia',`<p>Elige una actividad, despeja una superficie plana y deja sitio para las piezas sin usar. Ten papel y materiales de dibujo si quieren crear invitaciones o señales, separados de los componentes del juguete.</p><p>Prueba un plan flexible de 25 minutos: cinco para elegir la historia, quince para construir y modificar, y cinco para contarla y guardar. Es una sugerencia organizativa, no una exigencia de concentración. Pueden parar antes o continuar.</p>`],
['1. Un monstruo que ayuda',`<p><strong>La misión:</strong> «Este monstruo ayuda en la fiesta. ¿Qué hace?». Construyan un personaje, vehículo o herramienta. Si vas a regalar bloques, compara {{p:soft-blocks-l2}} y {{p:soft-blocks-l3}}.</p><p><strong>Un cambio:</strong> modifica una parte para transportar una invitación imaginaria o pasar por una puerta. Que el niño explique la modificación; no hace falta que la forma parezca un monstruo reconocible.</p>`],
['2. Una entrada para el desfile',`<p><strong>La misión:</strong> «Los invitados necesitan entrar a la fiesta». Construye una puerta y decide qué visitante imaginario debe pasar. Cambia la abertura y la base si hace falta.</p><p><strong>Un cambio:</strong> haz una entrada más ancha con las mismas piezas. Compara ambos diseños. Si usas una figura, elige una apropiada que ya esté en casa.</p>`],
['3. Un camino para dinosaurios',`<p><strong>La misión:</strong> «El dinosaurio necesita encontrar la fiesta». Con {{p:dinosaur-l1}} u otros animales, organiza un inicio, una ruta y un destino. Puedes dibujar un mapa aparte.</p><p><strong>Un cambio:</strong> imagina que el camino está bloqueado y mueve el escenario para abrir otro. Lee {{a:3}} para una aventura más completa.</p>`],
['4. Un desfile bajo el agua',`<p><strong>La misión:</strong> «Los animales marinos necesitan un punto de reunión». Organiza {{p:ocean-l1}} o dibuja un escenario. Decide quién dirige el desfile y dónde esperan los invitados.</p><p><strong>Un cambio:</strong> ordena piezas por color o forma y crea una secuencia. El niño puede continuarla o inventar otra, con la dificultad que prefiera.</p>`],
['5. Una invitación en la nieve',`<p><strong>La misión:</strong> «Apareció una carta en la nieve. ¿Para quién es?». Usa {{p:ice-l2}} u otro escenario de animales y cuenta cómo llega la invitación.</p><p><strong>Un cambio:</strong> añadan un acontecimiento por turnos. Un invitado se pierde y el niño decide cómo ayudarlo. Mantén una historia tranquila si así la disfruta más.</p>`],
['Convierte la actividad favorita en un regalo',`<p>Escribe el reto favorito en una tarjeta para acompañar un futuro set. Consulta {{a:0}} y comprueba el contenido antes de prometer una construcción concreta. Son ideas creativas, no afirmaciones sobre resultados educativos medidos.</p><p>En grupo, alterna los papeles de planificador, constructor y narrador. Para organizar materiales y limpieza, consulta {{a:5}}.</p>`]
],faq:[['¿Necesito las cuatro colecciones?','No. Elige una actividad y adáptala a un set apropiado que ya tengas. Puedes dibujar en papel los elementos que falten.'],['¿Los bloques incluyen decoraciones de Halloween?','Aquí no se promete ningún accesorio festivo. Mapas, señales e invitaciones son añadidos opcionales; revisa el contenido real en la página del producto.']]},
{title:'Regalos de Halloween para la clase y fiestas sin dulces',description:'Organiza regalos escolares de Halloween con permiso del docente. Compara recuerdos individuales y bloques compartidos, con un plan de actividad y limpieza.',intro:'Empieza por las normas del docente, el número de alumnos y el propósito del regalo. Un recuerdo para llevar a casa, un juguete donado al aula y una actividad compartida son decisiones distintas. Elegir una finalidad clara facilita la organización de la fiesta.',sections:[
['Consulta al docente antes de comprar',`<p>Confirma si la escuela celebra Halloween, prefiere un tema otoñal o no acepta regalos. Pregunta por edades, materiales permitidos, restricciones alimentarias y tiempo disponible. Averigua si hacen falta objetos iguales para todos o si sería más útil una donación compartida.</p><p>Un mensaje breve sirve: «¿Sería bienvenida una actividad sin alimentos o un set de construcción? ¿Para cuántos niños y qué materiales o temas debemos evitar?». Espera la respuesta antes de comprar cantidades.</p>`],
['Recuerdos individuales para regalos individuales',`<p>Considera pegatinas, separadores, lápices u hojas de actividades aprobados y adecuados para la edad. Evita que el docente tenga que montarlos durante la fiesta. Prepara la cantidad confirmada y acuerda qué hacer si se suma alguien.</p><p>No dividas un set en bolsas de piezas sueltas: pueden faltar componentes, instrucciones y etiquetas. Un set SUPUZZ completo encaja mejor como donación aprobada o estación de construcción.</p><p>Consulta {{a:2}} para distinguir regalos familiares y opciones para muchos visitantes. Lo adecuado para un niño conocido puede no serlo para toda una clase.</p>`],
['Una estación de construcción compartida',`<p>Pregunta primero si ya hay materiales disponibles. Si se necesita una donación, compara {{p:soft-blocks-l3}} para personajes inventados, o {{p:ocean-l2}} y {{p:ice-l2}} para historias de animales. Revisa con el docente la edad y los componentes exactos.</p><p>La cantidad de piezas no determina cuántos niños pueden jugar a la vez. El docente debe decidir el grupo según espacio, supervisión y actividad. Coloca solo lo que quepa cómodamente en la mesa.</p><ol><li>Presenta la historia: una criatura amistosa necesita un lugar para una fiesta de otoño.</li><li>Ofrece papeles flexibles: proponer, construir, dibujar o narrar.</li><li>Alterna la participación para que todos aporten ideas.</li><li>Comparte el resultado y pregunta qué cambió.</li><li>Devuelve las piezas y conserva las instrucciones.</li></ol>`],
['Reserva tiempo para guardar y cambiar de actividad',`<p>Propón tres minutos de introducción, diez de construcción y cinco para compartir y ordenar; el docente puede ajustarlo. Mantén las decoraciones fuera de la superficie si dificultan recoger.</p><p>Decide dónde guardar los materiales antes de comenzar. Usa la caja si la versión la incluye; en caso contrario, acuerda otro recipiente. Aclara si el set se queda en el aula o vuelve a la familia.</p>`],
['Ofrece una versión de otoño',`<p>Una reunión en la selva o un desfile de animales no necesita fantasmas ni disfraces. Permite participar mediante dibujo o relato si alguien no quiere construir, siguiendo el criterio del docente.</p><p>Encuentra propuestas en {{a:4}} y compara la colección en {{a:0}} una vez confirmada la utilidad de una donación.</p>`]
],faq:[['¿Debo comprar un set por alumno?','Solo si los regalos completos individuales encajan en el plan aprobado y el presupuesto. En muchos eventos resultan más prácticos recuerdos sencillos o una actividad compartida.'],['¿Puede evitarse la temática de Halloween?','Sí. Cambia el relato por una reunión de otoño o un desfile de animales. Los juguetes no requieren una historia de Halloween.']]}
]};
