module.exports = {
home:'Accueil', journal:'Journal', breadcrumb:'Fil d’Ariane', category:'Cadeaux d’Halloween', author:'L’équipe SUPUZZ', date:'22 septembre 2026', contents:'Dans ce guide', faq:'Questions fréquentes', related:'D’autres idées de cadeaux et de jeux d’Halloween', collection:'Découvrir la collection SUPUZZ', back:'Retour au Journal', read:'Lire le guide', details:'Voir les photos et le contenu du coffret',
caption:'Photo du produit. Les histoires d’Halloween et les décorations ajoutées sont des idées de jeu, non des accessoires inclus.',
shoppingTitle:'Avant de commander aux États-Unis ou au Canada', shopping:'Vérifiez l’âge indiqué et le contenu de la version choisie. Les pages produits renvoient vers Amazon.com. Au Canada, confirmez la livraison à votre adresse, la devise, les frais de transport et les éventuels frais d’importation : une fiche américaine ne garantit pas une livraison au Canada. Comparez la date estimée avec celle de votre fête, pas seulement avec le 31 octobre. Prix, stocks et délais peuvent changer.',
articles:[
{title:'Cadeaux d’Halloween pour enfants : quels jouets choisir ?',description:'Comparez 11 coffrets SUPUZZ pour Halloween : dinosaures, océan, glace et blocs arc-en-ciel. Des cadeaux sans bonbons pour jouer en famille après la fête.',intro:'Un cadeau d’Halloween peut partir de ce que l’enfant aime déjà : les dinosaures, les animaux marins ou les constructions inventées. Ajoutez une carte avec un petit défi. Un jouet du quotidien devient alors une surprise d’octobre qui reste intéressante une fois les décorations rangées.',sections:[
['Choisir selon l’occasion',`<p>Pour un enfant ou un petit-enfant, choisissez un coffret complet à découvrir ensemble. Pour une fratrie, demandez si chacun préfère son projet ou une scène commune. Les cadeaux de classe et les petits objets distribués à la porte répondent à d’autres besoins.</p><ul><li><strong>Surprise en famille :</strong> un jouet et un rendez-vous pour jouer.</li><li><strong>Panier surprise :</strong> choisissez le cadeau avant le contenant. Consultez {{a:1}}.</li><li><strong>Fête de groupe :</strong> demandez si l’hôte souhaite des cadeaux individuels ou une activité commune.</li></ul><p>Ce guide présente notre collection SUPUZZ ; il ne s’agit pas d’un classement indépendant. Les scènes d’Halloween sont des propositions créatives, sans décorations de fête incluses.</p>`],
['Des blocs arc-en-ciel pour inventer un gentil monstre',`<p>Imaginez un monstre qui aide les invités, une porte ou un véhicule pour un défilé. Inutile d’imposer des couleurs d’Halloween : l’enfant peut choisir le nom et le costume de son personnage.</p>{{cards:soft-blocks-l2,soft-blocks-l3}}<p>Comparez les versions de 80 et 128 pièces selon la quantité de matériel que la famille souhaite organiser. Toutes deux comprennent une mallette ; vérifiez l’option choisie.</p>`],
['Une aventure dans la jungle des dinosaures',`<p>Construisez un chemin vers une clairière où se tient une fête préhistorique. Gardez la pièce éclairée : le récit suffit à créer le mystère. Retrouvez une aventure en trois étapes dans {{a:3}}.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 compte 41 pièces, L2 en compte 99 et L3, 129. Le niveau désigne une version, pas une échelle universelle de capacité. Comparez les photos du contenu exact.</p>`],
['Un défilé sous la mer',`<p>Pour un enfant qui préfère les animaux aux fantômes, imaginez une fête dans un récif. Qui accueille les invités ? Où se réunissent-ils ? Un seul coffret suffit pour commencer une histoire.</p>{{cards:ocean-l1,ocean-l2,ocean-l3}}<p>Les versions comprennent respectivement 38, 76 et 136 pièces. L2 et L3 incluent une boîte de rangement. Pour L2, vérifiez l’âge sur le paquet sélectionné plutôt que sur une illustration commune à la gamme.</p>`],
['Une énigme douce dans la neige',`<p>Une invitation apparaît dans la neige : où conduit-elle les animaux ? Après octobre, transformez simplement le récit en aventure hivernale.</p>{{cards:ice-l1,ice-l2,ice-l3}}<p>Comparez les coffrets de 40, 79 et 136 pièces avec leur âge indiqué et leur contenu. Davantage de pièces ne signifie pas davantage de plaisir pour tous les enfants.</p>`],
['Offrir aussi du temps ensemble',`<p>Écrivez une invitation précise : « Samedi, construisons la maison de ta créature ». Pour d’autres idées, consultez {{a:4}}.</p><p>Si la famille cherche également une assise pour son coin d’activités, découvrez {{p:kids-chair-pink}}. Il s’agit d’une seule chaise, sans table. Comparez ses dimensions avec l’enfant et la table existante. Ce mobilier est facultatif pour accompagner un cadeau de jouets.</p>`]
],faq:[['Faut-il un jouet spécialement conçu pour Halloween ?','Non. Une carte et une histoire peuvent donner une touche festive à un jouet qui correspond aux goûts de l’enfant. Les coffrets présentés ne sont pas des kits d’Halloween.'],['Comment choisir pour un jeune enfant ?','Commencez par l’âge indiqué sur la version exacte, puis considérez ses intérêts et l’aide souhaitée. L1 ou un petit nombre de pièces ne signifie pas que le produit convient à tous les tout-petits.']]},
{title:'Panier d’Halloween pour enfants : un boo basket sans bonbons',description:'Préparez un panier d’Halloween avec un jouet, une carte et une activité. Quatre thèmes, des conseils de budget et un message à personnaliser.',intro:'Le boo basket est un petit cadeau d’Halloween présenté dans un panier, un sac ou une boîte. Pour une version sans bonbons, choisissez un jouet qui servira vraiment, ajoutez une note personnelle et prévoyez une première activité. Pas besoin de multiplier les petits objets.',sections:[
['Trois éléments pour un panier complet',`<ol><li><strong>Un cadeau principal :</strong> un jouet complet avec une indication d’âge adaptée.</li><li><strong>Un détail personnel :</strong> un dessin, un livre emprunté à lire ensemble ou une carte au prénom de l’enfant.</li><li><strong>Une invitation :</strong> une courte activité à partager à l’ouverture.</li></ol><p>Choisissez d’abord le cadeau. Si sa boîte ne rentre pas dans le panier, placez la carte dans un sac réutilisable et le cadeau emballé à côté. Conservez le paquet et la notice ensemble ; ne répartissez pas les pièces en petits sachets surprises.</p>`],
['Quatre thèmes et une première mission',`<h3>L’atelier des gentils monstres</h3><p>Comparez {{p:soft-blocks-l2}} et {{p:soft-blocks-l3}}. Écrivez : « Ton monstre a besoin d’une maison. À quoi ressemble sa porte ? ». Laissez l’enfant inventer son nom et son caractère.</p><h3>L’expédition des dinosaures</h3><p>Accompagnez {{p:dinosaur-l1}} d’une carte montrant un départ et une clairière de fête. Si vous cherchez davantage de pièces, comparez {{p:dinosaur-l2}} et {{p:dinosaur-l3}}, sans ajouter un jouet simplement pour remplir le panier.</p><h3>La fête sous-marine</h3><p>Choisissez {{p:ocean-l1}} et dessinez une invitation pour un animal marin. Si un cadeau plus important était prévu, regardez {{p:ocean-l2}} et {{p:ocean-l3}}.</p><h3>L’invitation dans la neige</h3><p>Comparez {{p:ice-l1}}, {{p:ice-l2}} et {{p:ice-l3}} selon l’âge et le contenu. Proposez : « Une invitation a été laissée dans la neige. Où mène-t-elle ? ». Ne promettez pas un animal ou un accessoire sans vérifier la version.</p>`],
['Définir le budget avant les achats',`<p>Incluez le cadeau, l’emballage et la livraison dans votre total. Réutilisez un contenant et fabriquez la carte. Les prix évoluent : comparez le coût actuel sans supposer qu’un niveau est toujours moins cher.</p><p>Pour une fratrie, recherchez une attention équivalente plutôt que des boîtes identiques. Si les enfants préfèrent partager, inscrivez les deux prénoms et laissez chacun choisir son rôle dans la première construction.</p>`],
['Un message à adapter',`<div class="quote-box"><p>« Voici ta petite surprise d’Halloween ! Construis un endroit pour une gentille créature, donne-lui un nom et raconte-moi qui vient lui rendre visite. On s’y met ensemble ce week-end ? »</p></div><p>Avant de déposer un cadeau chez des voisins, demandez aux parents. Signez clairement et ne rendez pas obligatoire le fait d’offrir un panier à une autre famille. Pour l’école, consultez l’enseignant.</p><p>Comparez les jouets dans {{a:0}}, ou lisez {{a:2}} pour distinguer un cadeau personnel des petits objets à distribuer.</p>`]
],faq:[['Quand offrir un boo basket ?','Au moment qui convient à votre famille en octobre. L’offrir tôt laisse le temps de profiter de l’activité avant Halloween, mais le jour même convient aussi.'],['Faut-il beaucoup de petits jouets ?','Non. Un jouet complet, une carte et du temps partagé suffisent. Un sac ou une boîte déjà disponible peut faire office de contenant.']]},
{title:'Halloween sans bonbons : idées de cadeaux pour enfants',description:'Choisissez des cadeaux sans bonbons pour la famille, la collecte d’Halloween ou la classe. Jouets, organisation et ressource officielle Teal Pumpkin.',intro:'Le bon cadeau sans bonbons dépend de son destinataire. Un coffret de construction complet peut faire plaisir à un enfant que vous connaissez. Pour de nombreux visiteurs à la porte, prévoyez plutôt des objets individuels faciles à choisir avec leurs accompagnateurs.',sections:[
['Distinguer cadeau personnel et petits objets à distribuer',`<p>Avant d’acheter, demandez-vous combien d’enfants sont concernés, si vous connaissez leur âge et si le cadeau sera utilisé ensemble ou emporté. Ces réponses comptent davantage qu’un emballage décoré de citrouilles.</p><ul><li>Pour un enfant ou petit-enfant : partez d’un intérêt connu.</li><li>Pour une petite réunion : envisagez une activité commune.</li><li>Pour la collecte d’Halloween : proposez des choix individuels appropriés avec l’aide des adultes.</li><li>Pour une classe : confirmez les règles et l’effectif.</li></ul><p>Un coffret de construction n’est pas un lot de cadeaux individuels. Le diviser peut laisser des constructions incomplètes et séparer les enfants des notices et étiquettes.</p>`],
['Des jouets pour une attention personnelle',`<h3>Pour les histoires d’animaux</h3><p>{{p:ocean-l1}} offre un décor marin, et {{p:ice-l1}} un décor polaire. Ajoutez une invitation maison à une fête d’animaux et laissez l’enfant choisir le récit.</p><h3>Pour les amateurs de dinosaures</h3><p>Avec {{p:dinosaur-l1}}, dessinez une carte sur une feuille séparée et organisez une expédition. Comparez les versions dans {{a:3}}.</p><h3>Pour inventer librement</h3><p>Accompagnez {{p:soft-blocks-l2}} du défi de créer un monstre serviable. La consigne donne le ton de la saison sans limiter le jouet à une seule fête.</p>`],
['Préparer des options non alimentaires',`<p>Autocollants, marque-pages ou petits livrets d’activités sont des possibilités, selon leur étiquetage et l’âge attendu. Estimez la quantité à partir de votre expérience du quartier et gardez les emballages accessibles aux adultes.</p><p>Le <a href="https://www.foodallergy.org/our-initiatives/awareness-campaigns/teal-pumpkin-project">Teal Pumpkin Project de FARE</a> encourage à proposer des objets non alimentaires dans un récipient séparé. Son site officiel explique comment participer. Une citrouille turquoise signale ces choix ; elle ne certifie pas un jouet.</p><p>Sans bonbons ne veut pas dire automatiquement sans allergènes. Évitez les garanties générales sur les matériaux ou leur adéquation à tous les enfants. Séparez les objets des friandises si vous offrez les deux.</p>`],
['Privilégier la personnalisation',`<p>Demandez quel animal ou quelle histoire l’enfant aime actuellement. Emballez un coffret complet et écrivez une première aventure, avec un rendez-vous pour jouer ensemble.</p><p>Si la famille souhaite moins d’objets, proposez une sortie à la bibliothèque, un après-midi dessin ou du temps pour reconstruire un jouet existant. Une fête sans bonbons n’oblige pas à acheter.</p><p>Consultez {{a:1}} pour la présentation, {{a:0}} pour les jouets et {{a:5}} pour les événements scolaires.</p>`]
],faq:[['Peut-on distribuer les pièces d’un coffret aux visiteurs ?','Il vaut mieux garder le coffret complet pour un cadeau personnel ou une activité organisée. Des pièces séparées ne constituent pas de petits coffrets complets.'],['Un cadeau sans bonbons convient-il à toutes les allergies ?','Non. Vérifiez le produit précis et demandez à l’accompagnateur. Les choix non alimentaires ne sont pas une garantie universelle de sécurité.']]},
{title:'Dinosaures à offrir pour Halloween : coffrets et jeux',description:'Comparez les coffrets Dinosaur Jungle L1, L2 et L3. Ajoutez une carte et une aventure en trois étapes pour un cadeau d’Halloween aux fans de dinosaures.',intro:'Pour un enfant passionné de dinosaures, Halloween peut devenir une expédition préhistorique. Un coffret, une carte dessinée et une invitation à une fête amicale suffisent pour lancer l’histoire. Le jouet n’a pas besoin d’une citrouille sur sa boîte.',sections:[
['Comparer les trois versions',`<p>Choisissez selon l’espace de jeu, les envies de l’enfant et la quantité de pièces à organiser. Le niveau désigne une version, non une échelle universelle d’aptitude.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 comprend 41 pièces pour une scène plus concentrée, L2 en propose 99 et L3, 129. Le catalogue indique 3 ans et plus ; vérifiez le paquet choisi. Les photos communes à la gamme peuvent montrer d’autres arrangements. Consultez l’image du contenu exact et ne déduisez pas la présence d’une mallette du nombre de pièces.</p>`],
['Une aventure d’Halloween en trois étapes',`<h3>1. L’invitation arrive</h3><p>Écrivez : « Les dinosaures organisent une fête costumée. Peux-tu leur construire un lieu de rencontre ? ». Dessinez un départ et une clairière sur une feuille à part, en laissant l’enfant modifier le plan.</p><h3>2. Préparer un chemin accueillant</h3><p>Disposez les plantes et éléments de jungle pour suggérer une route. Qui arrive en premier ? Où attendent les invités ? Une aventure nocturne imaginaire se joue très bien dans une pièce éclairée.</p><h3>3. Résoudre un petit problème</h3><p>Imaginez qu’un invité s’est trompé de chemin. Invitez l’enfant à déplacer un élément pour l’aider à retrouver la fête. Terminez par les retrouvailles, puis laissez-le raconter sa propre version.</p><p>Ce sont des propositions créatives, pas des activités fournies ni des constructions garanties. Utilisez les pièces de votre version ; carte et invitations sont préparées séparément.</p>`],
['Adapter la présentation au destinataire',`<p>Pour un petit-enfant, notez la date de votre prochain moment de jeu. Pour une fratrie, demandez si les enfants souhaitent partager le décor ou créer chacun un projet. Si les frayeurs ne leur plaisent pas, parlez d’une fête d’automne.</p><p>Gardez l’emballage et la notice. Pour un panier surprise, mesurez la boîte et consultez {{a:1}}. Un grand contenant ne justifie pas davantage de jouets.</p>`],
['Continuer après Halloween',`<p>La fois suivante, racontez un sauvetage dans la jungle, une visite au jardin ou un pique-nique. Changez le parcours et demandez ce qui devrait être différent. Le récit évolue sans qu’il faille remplacer le jouet.</p><p>Pour les amateurs d’océan ou d’animaux polaires, consultez {{a:0}}. Avec le matériel déjà disponible, essayez {{a:4}}.</p>`]
],faq:[['S’agit-il de coffrets exclusifs à Halloween ?','Non. Ce sont des coffrets de construction Dinosaur Jungle. L’invitation, la carte et la fête sont des idées facultatives à ajouter chez vous.'],['Un enfant plus âgé doit-il recevoir le plus grand coffret ?','Pas nécessairement. Respectez l’âge indiqué, puis considérez ses intérêts, l’espace disponible et son plaisir à organiser des pièces.']]},
{title:'5 activités d’Halloween avec des blocs pour enfants',description:'Construisez un gentil monstre, une entrée de fête, un chemin de dinosaures, un défilé marin et une énigme polaire. Cinq idées à adapter en famille.',intro:'Une petite mission et une histoire transforment une séance de construction en activité d’Halloween. Adaptez ces cinq idées aux pièces appropriées à l’âge que vous avez déjà. L’enfant choisit l’apparence du résultat : il n’y a pas un modèle obligatoire à reproduire.',sections:[
['Préparer une courte séance en famille',`<p>Choisissez une activité, dégagez une surface plane et gardez une place pour les pièces inutilisées. Prévoyez du papier et du matériel de dessin si vous souhaitez créer des cartes ou des panneaux, séparément des éléments du jouet.</p><p>Essayez un programme souple de 25 minutes : cinq pour choisir l’histoire, quinze pour construire et modifier, puis cinq pour raconter et ranger. C’est une proposition d’organisation, pas une durée d’attention exigée. Arrêtez plus tôt ou prolongez si cela convient.</p>`],
['1. Un monstre serviable',`<p><strong>La mission :</strong> « Ce monstre aide pendant la fête. Que fait-il ? ». Construisez un personnage, un véhicule ou un outil. Pour un cadeau, comparez {{p:soft-blocks-l2}} et {{p:soft-blocks-l3}}.</p><p><strong>Une variante :</strong> modifiez un élément pour transporter une invitation imaginaire ou franchir une porte. Laissez l’enfant expliquer le changement, même si la forme n’évoque pas immédiatement un monstre.</p>`],
['2. Une entrée pour le défilé',`<p><strong>La mission :</strong> « Les invités doivent entrer dans la fête ». Construisez une porte et choisissez le visiteur imaginaire qui doit passer. Modifiez l’ouverture ou la base si nécessaire.</p><p><strong>Une variante :</strong> créez une entrée plus large avec les mêmes pièces et comparez les solutions. Une figurine adaptée déjà présente à la maison suffit ; aucun achat supplémentaire n’est nécessaire.</p>`],
['3. Un chemin pour les dinosaures',`<p><strong>La mission :</strong> « Le dinosaure doit trouver la fête ». Avec {{p:dinosaur-l1}} ou d’autres animaux, placez un départ, un parcours et une arrivée. Dessinez une carte à part si cela aide.</p><p><strong>Une variante :</strong> le chemin est bloqué ; déplacez le décor pour en ouvrir un autre. Pour une histoire complète, consultez {{a:3}}.</p>`],
['4. Un défilé sous-marin',`<p><strong>La mission :</strong> « Les animaux marins ont besoin d’un lieu de rencontre ». Disposez {{p:ocean-l1}} ou dessinez une scène. Qui mène le défilé ? Où attendent les invités ?</p><p><strong>Une variante :</strong> classez quelques pièces par couleur ou forme et créez une suite. L’enfant peut la poursuivre ou en inventer une autre, selon ses envies.</p>`],
['5. Une lettre dans la neige',`<p><strong>La mission :</strong> « Une invitation apparaît dans la neige. À qui est-elle destinée ? ». Utilisez {{p:ice-l2}} ou un autre décor animalier et racontez son arrivée.</p><p><strong>Une variante :</strong> ajoutez un événement chacun votre tour. Un invité se perd, puis l’enfant choisit comment l’aider. Préférez un récit rassurant s’il apprécie les histoires douces.</p>`],
['Transformer l’activité préférée en cadeau',`<p>Écrivez la mission favorite sur une carte accompagnant un futur coffret. Consultez {{a:0}} et vérifiez le contenu avant de promettre une construction précise. Ces idées créatives ne constituent pas des affirmations sur des progrès éducatifs mesurés.</p><p>En groupe, alternez les rôles de concepteur, constructeur et narrateur. Pour le matériel et le rangement, consultez {{a:5}}.</p>`]
],faq:[['Faut-il les quatre collections ?','Non. Choisissez une activité et adaptez-la à un coffret approprié déjà disponible. Dessinez sur papier les éléments manquants.'],['Les décorations d’Halloween sont-elles incluses ?','Aucun accessoire festif n’est promis ici. Cartes, panneaux et invitations sont des ajouts facultatifs ; consultez la page produit pour le contenu réel.']]},
{title:'Cadeaux d’Halloween pour la classe : idées sans bonbons',description:'Préparez les cadeaux de classe avec l’accord de l’enseignant. Petites attentions, coffrets partagés et déroulement d’une activité de construction.',intro:'Commencez par les règles de l’enseignant, l’effectif et le but du cadeau. Une petite attention à emporter, un jouet donné à la classe et une activité commune sont trois choix différents. Une intention claire facilite l’organisation de la fête.',sections:[
['Demander avant d’acheter',`<p>Confirmez si l’école célèbre Halloween, préfère un thème d’automne ou n’accepte pas de cadeaux. Demandez l’âge des enfants, les matériaux permis, les règles alimentaires et le temps disponible. Des objets identiques sont-ils nécessaires, ou une ressource partagée serait-elle plus utile ?</p><p>Un message bref suffit : « Une activité sans aliments ou un coffret de construction serait-il bienvenu ? Pour combien d’enfants, et quels matériaux ou thèmes faut-il éviter ? ». Attendez la réponse avant de choisir les quantités.</p>`],
['Des petits cadeaux faciles à distribuer',`<p>Envisagez des autocollants, marque-pages, crayons ou feuilles d’activités approuvés et adaptés à l’âge. Évitez de demander un assemblage pendant la fête. Préparez l’effectif confirmé et convenez d’une solution si un enfant supplémentaire participe.</p><p>Ne divisez pas un coffret en sachets de pièces : les enfants pourraient manquer de composants, de notice ou d’étiquette d’âge. Un coffret SUPUZZ complet convient mieux à un don approuvé ou à un atelier organisé.</p><p>Consultez {{a:2}} pour distinguer cadeaux familiaux et distribution à de nombreux visiteurs. Le choix adapté à un enfant connu n’est pas forcément celui d’une classe entière.</p>`],
['Un atelier de construction partagé',`<p>Demandez d’abord si la classe possède déjà du matériel. Si un don est souhaité, comparez {{p:soft-blocks-l3}} pour inventer des personnages, ou {{p:ocean-l2}} et {{p:ice-l2}} pour des histoires d’animaux. Vérifiez l’âge et le contenu exact avec l’enseignant.</p><p>Le nombre de pièces ne détermine pas la taille du groupe. L’enseignant choisit selon la place, l’encadrement et l’activité. Sortez seulement le matériel qui tient confortablement sur la table.</p><ol><li>Présentez le récit : une gentille créature cherche un lieu pour une fête d’automne.</li><li>Proposez plusieurs rôles : imaginer, construire, dessiner ou raconter.</li><li>Faites tourner la participation pour que chacun apporte une idée.</li><li>Partagez le résultat et les changements réalisés.</li><li>Rangez les pièces avec la notice.</li></ol>`],
['Prévoir la transition et le rangement',`<p>Proposez trois minutes de présentation, dix de construction et cinq pour partager et ranger, à adapter par l’enseignant. Écartez les décorations si elles gênent la récupération des pièces.</p><p>Choisissez le lieu de rangement avant de commencer. Utilisez la boîte si la version en comprend une ; sinon, prévoyez un autre contenant. Précisez si le matériel reste à l’école ou retourne à la famille.</p>`],
['Une version simplement automnale',`<p>Une rencontre dans la jungle ou un défilé animalier ne nécessite ni fantômes ni costumes. Laissez participer par le dessin ou le récit les enfants qui ne souhaitent pas construire, en suivant les choix de l’enseignant.</p><p>Retrouvez des idées dans {{a:4}} et comparez les coffrets dans {{a:0}} une fois l’utilité du don confirmée.</p>`]
],faq:[['Faut-il un coffret par élève ?','Seulement si les cadeaux individuels complets correspondent au projet approuvé et au budget. Des petites attentions ou une activité partagée sont souvent plus pratiques.'],['Peut-on éviter toute référence à Halloween ?','Oui. Remplacez la fête par une réunion d’automne ou un défilé d’animaux. Les jouets n’exigent pas un récit d’Halloween.']]}
]};
