module.exports = {
home:'Início', journal:'Blog', breadcrumb:'Caminho de navegação', category:'Presentes de Halloween', author:'Equipe SUPUZZ', date:'22 de setembro de 2026', contents:'Neste guia', faq:'Perguntas frequentes', related:'Mais ideias de presentes e brincadeiras de Halloween', collection:'Explorar a coleção SUPUZZ', back:'Voltar ao blog', read:'Ler o guia', details:'Ver fotos e conteúdo do conjunto',
caption:'Foto do produto. As histórias de Halloween e as decorações extras são sugestões de brincadeira, não acessórios incluídos.',
shoppingTitle:'Antes de comprar nos Estados Unidos ou no Canadá', shopping:'Confira a indicação de idade e o conteúdo da embalagem escolhida. As páginas dos produtos levam à Amazon.com. No Canadá, confirme a entrega no seu endereço, a moeda, o frete e possíveis custos de importação: uma oferta dos EUA não garante entrega no Canadá. Compare a previsão de chegada com a data da sua festa, não apenas com 31 de outubro. Preços, estoque e prazos podem mudar.',
articles:[
{title:'Presentes de Halloween para crianças: brinquedos sem doces',description:'Compare 11 conjuntos SUPUZZ para presentear no Halloween: dinossauros, oceano, gelo e blocos arco-íris. Ideias para cestas e brincadeiras em família.',intro:'Um presente de Halloween pode começar pelo que a criança já gosta: dinossauros, animais marinhos ou construções inventadas. Acrescente um cartão com um pequeno desafio. Assim, um brinquedo do dia a dia vira uma surpresa de outubro que continua interessante depois que a decoração é guardada.',sections:[
['Escolha de acordo com a ocasião',`<p>Para um filho ou neto, procure um conjunto completo para abrir e explorar juntos. Para irmãos, pergunte se preferem projetos separados ou um cenário compartilhado. Presentes para a turma e lembrancinhas distribuídas na porta pedem outra organização.</p><ul><li><strong>Surpresa em família:</strong> um brinquedo e um convite para brincar.</li><li><strong>Cesta de Halloween:</strong> escolha o presente antes do recipiente. Veja {{a:1}}.</li><li><strong>Festa em grupo:</strong> pergunte se o anfitrião prefere lembranças individuais ou uma atividade coletiva.</li></ul><p>Este guia apresenta a coleção da própria SUPUZZ; não é um ranking independente. Os cenários de Halloween são sugestões criativas, sem decorações festivas incluídas.</p>`],
['Blocos arco-íris para inventar monstros amigáveis',`<p>Crie um monstro que ajuda os convidados, um portão ou um veículo para um desfile imaginário. Não é preciso limitar as cores: a criança pode dar nome ao personagem e explicar sua fantasia.</p>{{cards:soft-blocks-l2,soft-blocks-l3}}<p>Compare 80 e 128 peças conforme a quantidade de material que a família deseja organizar. As duas versões incluem maleta; confira a opção selecionada.</p>`],
['Dinossauros para uma aventura na selva',`<p>Construam um caminho até a clareira de uma festa pré-histórica. Mantenham o ambiente iluminado e deixem o mistério por conta da história. Uma aventura em três passos está em {{a:3}}.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 tem 41 peças, L2 tem 99 e L3 tem 129. O nível identifica uma versão, não uma medida universal de habilidade. Compare as fotos do conteúdo de cada embalagem.</p>`],
['Uma festa de animais no fundo do mar',`<p>Para quem prefere animais a fantasmas, imagine um desfile submarino. Quem organiza a festa? Onde os convidados se encontram? Um único conjunto pode iniciar a história.</p>{{cards:ocean-l1,ocean-l2,ocean-l3}}<p>As versões têm 38, 76 e 136 peças, respectivamente. L2 e L3 incluem caixa de armazenamento. Para L2, confira a idade na embalagem escolhida, em vez de usar apenas uma imagem compartilhada da linha.</p>`],
['Um mistério tranquilo no mundo de gelo',`<p>Um convite aparece na neve: para onde ele leva os animais? Depois de outubro, basta mudar a narrativa para uma aventura de inverno.</p>{{cards:ice-l1,ice-l2,ice-l3}}<p>Compare os conjuntos de 40, 79 e 136 peças junto com suas idades e conteúdos. Mais peças não significam mais diversão para toda criança.</p>`],
['Complete o presente com tempo juntos',`<p>Escreva um convite concreto: “No sábado vamos construir a casa da sua criatura”. Outras propostas estão em {{a:4}}.</p><p>Se a família também precisa de um assento para o espaço de atividades, conheça {{p:kids-chair-pink}}. É uma cadeira avulsa, sem mesa. Compare as medidas com a criança e a mesa existente. O móvel é opcional, não uma exigência para presentear com blocos.</p>`]
],faq:[['O brinquedo precisa ter tema de Halloween?','Não. Um cartão e uma história dão um toque festivo a um brinquedo que combina com a criança. Os conjuntos apresentados não são kits específicos de Halloween.'],['Como escolher para uma criança menor?','Comece pela idade indicada na embalagem exata. Depois considere interesses e necessidade de ajuda. L1 ou menos peças não significam que o produto serve para toda criança pequena.']]},
{title:'Boo basket infantil: cesta de Halloween sem doces',description:'Monte uma cesta de Halloween com um brinquedo, um cartão e uma atividade. Quatro temas, dicas de orçamento e uma mensagem pronta para adaptar.',intro:'Boo basket é uma pequena surpresa de Halloween apresentada em uma cesta, sacola ou caixa. Para uma versão sem doces, escolha um presente principal que a criança vai usar, acrescente uma mensagem pessoal e planeje a primeira brincadeira. Não é necessário encher o recipiente de pequenos objetos.',sections:[
['Três elementos para uma cesta completa',`<ol><li><strong>Um presente principal:</strong> um brinquedo completo com indicação de idade adequada.</li><li><strong>Um detalhe pessoal:</strong> um desenho, um livro emprestado para ler juntos ou uma nota com o nome da criança.</li><li><strong>Um convite:</strong> uma atividade curta para compartilhar depois de abrir.</li></ol><p>Escolha o presente antes do recipiente. Se a caixa não couber, coloque o cartão em uma sacola reutilizável e o brinquedo embrulhado ao lado. Mantenha embalagem e instruções juntas; não distribua peças soltas como recheio surpresa.</p>`],
['Quatro temas com uma primeira missão',`<h3>Oficina de monstros amigáveis</h3><p>Compare {{p:soft-blocks-l2}} e {{p:soft-blocks-l3}}. Escreva: “Seu monstro precisa de uma casa. Como será a porta?”. Deixe a criança inventar nome e personalidade.</p><h3>Expedição dos dinossauros</h3><p>Combine {{p:dinosaur-l1}} com um mapa desenhado mostrando a partida e a clareira da festa. Se deseja mais peças, compare {{p:dinosaur-l2}} e {{p:dinosaur-l3}}, sem adicionar brinquedos apenas para preencher espaço.</p><h3>Festa submarina</h3><p>Escolha {{p:ocean-l1}} e desenhe um convite para um animal marinho. Se um presente maior já estava nos planos, veja {{p:ocean-l2}} e {{p:ocean-l3}}.</p><h3>Um convite na neve</h3><p>Compare {{p:ice-l1}}, {{p:ice-l2}} e {{p:ice-l3}} conforme idade e conteúdo. Proponha: “Alguém deixou um convite na neve. Aonde ele leva?”. Não prometa animais ou acessórios sem conferir a versão.</p>`],
['Defina o orçamento antes das compras',`<p>Inclua presente, embalagem e entrega no total. Reaproveite um recipiente de casa e faça o cartão. Os preços mudam: compare o valor atual da compra sem assumir que determinado nível é sempre mais barato.</p><p>Para irmãos, procure demonstrar atenção equivalente, sem exigir caixas iguais. Se preferem compartilhar, escreva os dois nomes e deixe cada criança escolher uma função na primeira construção.</p>`],
['Uma mensagem para personalizar',`<div class="quote-box"><p>“Sua surpresa de Halloween chegou! Construa um lugar para uma criatura amigável, dê um nome a ela e me conte quem vai visitar. Neste fim de semana fazemos isso juntos.”</p></div><p>Antes de deixar um presente para o filho de um vizinho, converse com os responsáveis. Identifique quem enviou e não transforme a tradição em obrigação de presentear outra família. Para a escola, consulte o professor.</p><p>Compare todos os brinquedos em {{a:0}}. Para separar presentes familiares de lembrancinhas para muitos visitantes, leia {{a:2}}.</p>`]
],faq:[['Quando entregar uma boo basket?','Quando combinar com os planos da família em outubro. Entregar cedo permite aproveitar a atividade antes do Halloween; no próprio dia também funciona.'],['Preciso incluir muitos brinquedos pequenos?','Não. Um brinquedo completo, um cartão e tempo juntos formam um presente suficiente. Uma sacola ou caixa já disponível pode servir.']]},
{title:'Halloween sem doces: ideias de presentes para crianças',description:'Escolha presentes sem doces para família, visitas de Halloween e festas escolares. Ideias de brinquedos, planejamento e recurso oficial Teal Pumpkin.',intro:'A alternativa aos doces depende de quem vai receber. Um conjunto de construção completo pode ser um presente pessoal para uma criança conhecida. Para muitos visitantes na porta, planeje opções individuais fáceis de escolher com a ajuda dos responsáveis.',sections:[
['Diferencie presente pessoal e lembrancinha',`<p>Antes de comprar, pergunte quantas crianças são, se você conhece suas idades e se vão brincar juntas ou levar o presente para casa. Essas respostas importam mais que as abóboras da embalagem.</p><ul><li>Filho ou neto: escolha a partir de um interesse conhecido.</li><li>Pequeno encontro familiar: considere uma atividade compartilhada.</li><li>Visitantes pedindo doces: ofereça opções individuais apropriadas, com participação dos responsáveis.</li><li>Turma escolar: confirme regras e quantidade de alunos.</li></ul><p>Um conjunto de construção não é um pacote de lembrancinhas. Dividi-lo pode deixar montagens incompletas e separar as crianças das instruções e etiquetas. Preserve o conjunto completo.</p>`],
['Brinquedos para um presente pessoal',`<h3>Para histórias de animais</h3><p>{{p:ocean-l1}} oferece um cenário marinho, e {{p:ice-l1}}, um cenário polar. Acrescente um convite caseiro para uma festa de animais e deixe a criança escolher a narrativa.</p><h3>Para fãs de dinossauros</h3><p>Com {{p:dinosaur-l1}}, desenhe um mapa em outra folha e organize uma expedição. Compare as versões em {{a:3}}.</p><h3>Para criar livremente</h3><p>Combine {{p:soft-blocks-l2}} com o desafio de inventar um monstro prestativo. A proposta cria o clima de outubro sem limitar o brinquedo a uma única festa.</p>`],
['Prepare opções que não sejam alimentos',`<p>Adesivos, marcadores de página e pequenos cadernos de atividades são possibilidades, conforme suas indicações e a idade esperada. Estime a quantidade pela experiência da sua vizinhança e mantenha informações da embalagem disponíveis.</p><p>O <a href="https://www.foodallergy.org/our-initiatives/awareness-campaigns/teal-pumpkin-project">Teal Pumpkin Project da FARE</a> incentiva opções não alimentares em um recipiente separado. A página oficial explica como participar. A abóbora turquesa indica essas alternativas; ela não certifica nenhum brinquedo.</p><p>Sem doces não significa automaticamente livre de alérgenos. Evite garantias gerais sobre materiais ou adequação a todas as crianças. Se também oferecer guloseimas, mantenha as opções não alimentares separadas.</p>`],
['Valorize o toque pessoal',`<p>Pergunte pelo animal ou pela história favorita do momento. Embrulhe um conjunto completo e escreva a primeira aventura em um cartão, junto com uma data para brincar.</p><p>Se a família não deseja mais objetos, ofereça uma visita à biblioteca, uma tarde de desenho ou tempo para reconstruir um brinquedo que já existe em casa. Celebrar sem doces não exige comprar.</p><p>Veja {{a:1}} para apresentação, {{a:0}} para comparar brinquedos e {{a:5}} para eventos escolares.</p>`]
],faq:[['Posso distribuir peças de um conjunto a quem pede doces?','É melhor manter o conjunto completo para um presente pessoal ou atividade organizada. Peças avulsas não equivalem a pequenos conjuntos completos.'],['Uma opção sem doces serve para qualquer alergia?','Não. Confira o produto específico e converse com o responsável. Alternativas não alimentares não são uma garantia universal de segurança.']]},
{title:'Dinossauros para presentear no Halloween: conjuntos e ideias',description:'Compare Dinosaur Jungle L1, L2 e L3 para um presente de Halloween. Um mapa desenhado e uma aventura em três passos dão início à brincadeira.',intro:'Para uma criança que adora dinossauros, Halloween pode virar uma expedição pré-histórica. Um conjunto de blocos, um mapa desenhado e um convite para uma festa amigável iniciam a aventura. A história traz o clima da época, mesmo sem abóboras na caixa.',sections:[
['Compare as três versões',`<p>Escolha conforme o espaço, os interesses e a quantidade de peças que a família quer organizar. O nível é uma versão do produto, não uma medida universal de capacidade.</p>{{cards:dinosaur-l1,dinosaur-l2,dinosaur-l3}}<p>L1 tem 41 peças para uma cena mais concentrada; L2 oferece 99 e L3, 129. O catálogo indica 3 anos ou mais, mas confira o pacote escolhido. Imagens compartilhadas da linha podem mostrar outras montagens. Veja a foto do conteúdo exato e não deduza a presença de maleta pelo número de peças.</p>`],
['Uma aventura de Halloween em três passos',`<h3>1. O convite chega</h3><p>Escreva: “Os dinossauros vão fazer uma festa à fantasia. Você pode construir o ponto de encontro?”. Desenhe uma partida e uma clareira em uma folha separada, deixando a criança mudar o plano.</p><h3>2. Prepare um caminho amigável</h3><p>Organize plantas e elementos da selva para sugerir uma rota. Quem chega primeiro? Onde os convidados esperam? Uma expedição noturna imaginária pode acontecer em um ambiente bem iluminado.</p><h3>3. Resolva um pequeno problema</h3><p>Imagine que um convidado errou o caminho. Convide a criança a mover uma parte do cenário para ajudá-lo. Termine com todos reunidos e deixe que ela conte outra versão da história.</p><p>São sugestões criativas, não atividades incluídas nem montagens garantidas. Use as peças da sua versão; mapa e cartões são preparados à parte.</p>`],
['Adapte a apresentação a quem recebe',`<p>Para um neto, anote quando vocês vão brincar juntos. Para irmãos, pergunte se querem compartilhar o cenário ou construir projetos separados. Se a criança não gosta de sustos, transforme tudo em uma reunião de outono.</p><p>Guarde embalagem e instruções. Para uma cesta surpresa, meça a caixa e consulte {{a:1}}. Um recipiente grande não exige brinquedos extras.</p>`],
['Continue depois do Halloween',`<p>Na próxima brincadeira, conte um resgate na selva, uma visita ao jardim ou um piquenique. Reorganize o caminho e pergunte o que deve mudar. A narrativa evolui sem precisar trocar de brinquedo.</p><p>Para quem prefere animais marinhos ou polares, veja {{a:0}}. Para usar materiais já disponíveis, experimente {{a:4}}.</p>`]
],faq:[['São kits de dinossauros exclusivos de Halloween?','Não. São conjuntos de construção Dinosaur Jungle. Convite, mapa e história de festa são complementos opcionais feitos em casa.'],['Uma criança mais velha precisa do maior conjunto?','Não necessariamente. Respeite a idade indicada e considere interesses, espaço e o quanto ela gosta de organizar peças.']]},
{title:'5 brincadeiras de Halloween com blocos para crianças',description:'Construa um monstro amigável, uma entrada, um caminho de dinossauros, um desfile marinho e um mistério polar. Cinco atividades adaptáveis em família.',intro:'Uma pequena missão e uma história transformam uma sessão de montagem em brincadeira de Halloween. Adapte estas cinco ideias às peças adequadas à idade que você já tem. A criança escolhe o resultado; não existe um único modelo obrigatório para copiar.',sections:[
['Prepare uma sessão curta em família',`<p>Escolha uma atividade, libere uma superfície plana e deixe espaço para as peças sem uso. Separe papel e materiais de desenho para convites ou placas, sem misturá-los ao conteúdo do brinquedo.</p><p>Experimente um plano flexível de 25 minutos: cinco para escolher a história, quinze para construir e modificar, e cinco para contar e guardar. É uma sugestão de organização, não uma exigência de atenção. Vocês podem parar antes ou continuar.</p>`],
['1. Um monstro que ajuda',`<p><strong>A missão:</strong> “Este monstro ajuda na festa. O que ele faz?”. Construam um personagem, veículo ou ferramenta. Para um presente, compare {{p:soft-blocks-l2}} e {{p:soft-blocks-l3}}.</p><p><strong>Uma mudança:</strong> modifique uma parte para levar um convite imaginário ou passar por uma porta. Deixe a criança explicar a alteração; a forma não precisa parecer imediatamente um monstro.</p>`],
['2. Uma entrada para o desfile',`<p><strong>A missão:</strong> “Os convidados precisam entrar na festa”. Construa um portão e escolha o visitante imaginário que deve passar. Ajuste a abertura e a base se necessário.</p><p><strong>Uma mudança:</strong> faça uma entrada mais larga com as mesmas peças e compare as soluções. Se usar uma figura, escolha uma já disponível e apropriada para a criança.</p>`],
['3. Um caminho para os dinossauros',`<p><strong>A missão:</strong> “O dinossauro precisa encontrar a festa”. Com {{p:dinosaur-l1}} ou outros animais, organize começo, caminho e destino. Um mapa pode ser desenhado em outra folha.</p><p><strong>Uma mudança:</strong> imagine que o caminho está bloqueado e mova o cenário para abrir outra rota. A história completa está em {{a:3}}.</p>`],
['4. Um desfile no fundo do mar',`<p><strong>A missão:</strong> “Os animais marinhos precisam de um ponto de encontro”. Monte {{p:ocean-l1}} ou desenhe o cenário. Quem lidera o desfile e onde os convidados esperam?</p><p><strong>Uma mudança:</strong> organize algumas peças por cor ou forma, criando uma sequência. A criança pode continuar ou inventar outra, com a dificuldade que preferir.</p>`],
['5. Uma carta na neve',`<p><strong>A missão:</strong> “Apareceu um convite na neve. Para quem é?”. Use {{p:ice-l2}} ou outro cenário de animais e conte como a carta chegou.</p><p><strong>Uma mudança:</strong> acrescentem um acontecimento por vez. Um convidado se perde e a criança decide como ajudar. Mantenha uma história tranquila se ela preferir.</p>`],
['Transforme a atividade favorita em presente',`<p>Escreva o desafio favorito em um cartão para acompanhar um futuro conjunto. Consulte {{a:0}} e confira o conteúdo antes de prometer uma construção específica. São propostas criativas, não afirmações de resultados educacionais medidos.</p><p>Em grupo, alternem os papéis de planejador, construtor e narrador. Para materiais e organização, veja {{a:5}}.</p>`]
],faq:[['Preciso das quatro coleções?','Não. Escolha uma atividade e adapte a um conjunto adequado já disponível. Elementos que faltam podem ser desenhados no papel.'],['As decorações de Halloween estão incluídas?','Nenhum acessório festivo é prometido aqui. Mapas, placas e convites são extras opcionais; confira o conteúdo real na página do produto.']]},
{title:'Presentes de Halloween para a escola: ideias sem doces',description:'Planeje presentes escolares com autorização do professor. Compare lembranças individuais e conjuntos compartilhados, com um roteiro de atividade e arrumação.',intro:'Comece pelas regras do professor, pelo número de alunos e pelo objetivo do presente. Uma lembrança para levar, um brinquedo doado à sala e uma atividade coletiva são escolhas diferentes. Definir uma finalidade facilita a organização da festa.',sections:[
['Pergunte antes de comprar',`<p>Confirme se a escola comemora Halloween, prefere um tema de outono ou não aceita presentes. Pergunte sobre idades, materiais permitidos, regras para alimentos e tempo disponível. Descubra se todos precisam de lembranças iguais ou se um recurso compartilhado seria mais útil.</p><p>Uma mensagem simples basta: “Uma atividade sem alimentos ou um conjunto de construção seria bem-vindo? Para quantas crianças e quais materiais ou temas devemos evitar?”. Aguarde a resposta antes de definir quantidades.</p>`],
['Lembranças individuais fáceis de distribuir',`<p>Considere adesivos, marcadores de página, lápis ou folhas de atividades aprovados e adequados à idade. Evite exigir montagem do professor durante a festa. Prepare o número confirmado e combine o que fazer se chegar mais uma criança.</p><p>Não divida um conjunto em saquinhos de peças: podem faltar componentes, instruções e indicação de idade. Um conjunto SUPUZZ completo combina melhor com uma doação autorizada ou estação de brincadeira organizada.</p><p>{{a:2}} ajuda a distinguir presentes familiares e opções para muitos visitantes. O que serve para uma criança conhecida pode não servir para toda a turma.</p>`],
['Uma estação de construção compartilhada',`<p>Pergunte primeiro se já existem materiais na sala. Se uma doação for desejada, compare {{p:soft-blocks-l3}} para personagens inventados, ou {{p:ocean-l2}} e {{p:ice-l2}} para histórias de animais. Confira idade e conteúdo exatos com o professor.</p><p>O número de peças não determina quantas crianças podem brincar juntas. O professor define o grupo conforme espaço, supervisão e atividade. Coloque apenas o material que cabe confortavelmente na mesa.</p><ol><li>Apresente a história: uma criatura amigável precisa de um lugar para uma festa de outono.</li><li>Ofereça funções flexíveis: planejar, construir, desenhar ou narrar.</li><li>Alterne a participação para que todos proponham ideias.</li><li>Compartilhe o resultado e as mudanças feitas.</li><li>Guarde as peças e mantenha as instruções com o conjunto.</li></ol>`],
['Reserve tempo para transição e arrumação',`<p>Sugira três minutos de apresentação, dez de construção e cinco para compartilhar e guardar, com ajustes do professor. Afaste decorações que dificultem recolher as peças.</p><p>Defina o local de armazenamento antes de começar. Use a caixa se a versão incluir uma; caso contrário, combine outro recipiente. Deixe claro se os materiais ficam na escola ou voltam para a família.</p>`],
['Ofereça uma versão sem sustos',`<p>Uma reunião na selva ou um desfile de animais funciona sem fantasmas e fantasias. Quem não quiser montar pode desenhar ou contar a história, conforme a orientação do professor.</p><p>Veja propostas em {{a:4}} e compare a coleção em {{a:0}} depois de confirmar que a doação será útil.</p>`]
],faq:[['Devo comprar um conjunto para cada aluno?','Somente se presentes individuais completos fizerem parte do plano aprovado e couberem no orçamento. Em muitos eventos, lembranças simples ou uma atividade compartilhada são mais práticas.'],['A atividade pode evitar o tema Halloween?','Sim. Transforme a história em uma reunião de outono ou desfile de animais. Os brinquedos não exigem uma narrativa de Halloween.']]}
]};
